services:
  bank-discovery-service:
    build: ./discovery-service
    container_name: bank-discovery-service
    image: 'postgres:latest'
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
  bank-config-service:
    build: ./config-service
    container_name: bank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:9999/actuator/health" ]
    depends_on:
      bank-discovery-service:
        condition: service_healthy
  customer-service:
    build: ./customer-service
    container_name: bank-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8081/actuator/health" ]
    depends_on:
      bank-config-service:
        condition: service_healthy
  account-service:
    build: ./Account-service
    container_name: bank-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
    depends_on:
      customer-service:
        condition: service_healthy
  gateway-service:
    build: ./getway-service
    container_name: bank-getway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
    depends_on:
      bank-config-service:
        condition: service_healthy
  front-send-angular:
    build: ./angular-front-end
    container_name: front-send-angular
    ports:
      - '80:80'
    expose:
      - '80'